"""
Export current taxonomy state from the database into source files.

Regenerates:
  - database/seed_taxonomy.sql
  - backend/app/services/taxonomy_config.py

Usage:
    python scripts/export_taxonomy.py           # overwrite files
    python scripts/export_taxonomy.py --dry-run  # print to stdout
"""

import argparse
import asyncio
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SEED_PATH = PROJECT_ROOT / "database" / "seed_taxonomy.sql"
CONFIG_PATH = PROJECT_ROOT / "backend" / "app" / "services" / "taxonomy_config.py"

# All sorted dimensions fetch (name, sort_order)
SORTED_TABLES = {
    "categories": ("category", "category_name, historic_subcategory_name, sort_order", "sort_order, category_name"),
    "cinema_types": ("cinema_type", "technique_name, sort_order", "sort_order, technique_name"),
    "themes": ("theme_context", "theme_name, sort_order", "sort_order, theme_name"),
    "characters": ("character_context", "context_name, sort_order", "sort_order, context_name"),
    "atmospheres": ("atmosphere", "atmosphere_name, sort_order", "sort_order, atmosphere_name"),
    "motivations": ("motivation_relation", "motivation_name, sort_order", "sort_order, motivation_name"),
    "messages": ("message_conveyed", "message_name, sort_order", "sort_order, message_name"),
    "time_contexts": ("time_context", "time_period, sort_order", "sort_order, time_period"),
    "place_contexts": ("place_context", "environment, sort_order", "sort_order, environment"),
}


async def fetch_all(engine):
    """Fetch all taxonomy data from the database."""
    data = {}
    async with engine.connect() as conn:
        # Categories (special: has subcategories)
        r = await conn.execute(text(
            "SELECT category_name, historic_subcategory_name, sort_order FROM category "
            "ORDER BY sort_order, category_name, historic_subcategory_name NULLS FIRST"
        ))
        data["categories"] = [(row[0], row[1], row[2]) for row in r.fetchall()]

        # All sorted single-column tables
        for key, (table, cols, order) in SORTED_TABLES.items():
            if key == "categories":
                continue
            r = await conn.execute(text(f"SELECT {cols} FROM {table} ORDER BY {order}"))
            data[key] = [(row[0], row[1]) for row in r.fetchall()]

        # Person jobs
        r = await conn.execute(text("SELECT role_name FROM person_job ORDER BY role_name"))
        data["person_jobs"] = [row[0] for row in r.fetchall()]

        # Streaming platforms
        r = await conn.execute(text("SELECT platform_name FROM stream_platform ORDER BY platform_name"))
        data["streaming_platforms"] = [row[0] for row in r.fetchall()]

        # Languages
        r = await conn.execute(text("SELECT language_code, language_name FROM language ORDER BY language_code"))
        data["languages"] = [(row[0], row[1]) for row in r.fetchall()]

    return data


def _sql_values(values: list[str], indent: str = "    ") -> str:
    """Format a list of strings as SQL VALUES."""
    lines = []
    for i, v in enumerate(values):
        escaped = v.replace("'", "''")
        comma = "," if i < len(values) - 1 else ""
        lines.append(f"{indent}('{escaped}'){comma}")
    return "\n".join(lines)


def _sql_sorted_values(items: list[tuple[str, int]], col_name: str, indent: str = "    ") -> str:
    """Format (name, sort_order) tuples as SQL VALUES."""
    lines = []
    for i, (name, sort_order) in enumerate(items):
        escaped = name.replace("'", "''")
        comma = "," if i < len(items) - 1 else ""
        lines.append(f"{indent}('{escaped}', {sort_order}){comma}")
    return "\n".join(lines)


def generate_seed_sql(data: dict) -> str:
    """Generate the full seed_taxonomy.sql content."""
    sections = []

    sections.append("-- Film Database Seed Data")
    sections.append("-- Pre-populate all taxonomy/lookup tables with reference values")
    sections.append("-- Uses ON CONFLICT DO NOTHING for idempotent execution")
    sections.append("-- Auto-generated by scripts/export_taxonomy.py")

    # Person jobs
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- PERSON_JOB - Crew roles")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["person_jobs"])
    sections.append(f"INSERT INTO person_job (role_name) VALUES\n{vals}\nON CONFLICT (role_name) DO NOTHING;")

    # Categories
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- CATEGORY - Film genres with historical subcategories")
    sections.append("-- =============================================================================")
    sections.append("")
    cat_lines = []
    for i, (cat_name, sub_name, sort_order) in enumerate(data["categories"]):
        comma = "," if i < len(data["categories"]) - 1 else ""
        cn = cat_name.replace("'", "''")
        if sub_name:
            sn = sub_name.replace("'", "''")
            cat_lines.append(f"    ('{cn}', '{sn}', {sort_order}){comma}")
        else:
            cat_lines.append(f"    ('{cn}', NULL, {sort_order}){comma}")
    sections.append(f"INSERT INTO category (category_name, historic_subcategory_name, sort_order) VALUES\n" +
                    "\n".join(cat_lines) +
                    "\nON CONFLICT (category_name, historic_subcategory_name) DO NOTHING;")

    # Cinema types (merged with cultural movements)
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- CINEMA_TYPE - Cinema types, techniques & cultural movements")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_sorted_values(data["cinema_types"], "technique_name")
    sections.append(f"INSERT INTO cinema_type (technique_name, sort_order) VALUES\n{vals}\nON CONFLICT (technique_name) DO NOTHING;")

    # Place contexts
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- PLACE_CONTEXT - Environmental settings")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_sorted_values(data["place_contexts"], "environment")
    sections.append(f"INSERT INTO place_context (environment, sort_order) VALUES\n{vals}\nON CONFLICT (environment) DO NOTHING;")

    # Time contexts
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- TIME_CONTEXT - Historical periods and seasons")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_sorted_values(data["time_contexts"], "time_period")
    sections.append(f"INSERT INTO time_context (time_period, sort_order) VALUES\n{vals}\nON CONFLICT (time_period) DO NOTHING;")

    # Themes
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- THEME_CONTEXT - Thematic elements")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_sorted_values(data["themes"], "theme_name")
    sections.append(f"INSERT INTO theme_context (theme_name, sort_order) VALUES\n{vals}\nON CONFLICT (theme_name) DO NOTHING;")

    # Characters (merged types + contexts + archetypes)
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- CHARACTER_CONTEXT - Characters (types + contexts + archetypes)")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_sorted_values(data["characters"], "context_name")
    sections.append(f"INSERT INTO character_context (context_name, sort_order) VALUES\n{vals}\nON CONFLICT (context_name) DO NOTHING;")

    # Atmospheres
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- ATMOSPHERE - Film atmosphere/tone")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_sorted_values(data["atmospheres"], "atmosphere_name")
    sections.append(f"INSERT INTO atmosphere (atmosphere_name, sort_order) VALUES\n{vals}\nON CONFLICT (atmosphere_name) DO NOTHING;")

    # Motivations
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- MOTIVATION_RELATION - Character motivations")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_sorted_values(data["motivations"], "motivation_name")
    sections.append(f"INSERT INTO motivation_relation (motivation_name, sort_order) VALUES\n{vals}\nON CONFLICT (motivation_name) DO NOTHING;")

    # Messages
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- MESSAGE_CONVEYED - Film messages")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_sorted_values(data["messages"], "message_name")
    sections.append(f"INSERT INTO message_conveyed (message_name, sort_order) VALUES\n{vals}\nON CONFLICT (message_name) DO NOTHING;")

    # Streaming platforms
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- STREAM_PLATFORM - Streaming platforms")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["streaming_platforms"])
    sections.append(f"INSERT INTO stream_platform (platform_name) VALUES\n{vals}\nON CONFLICT (platform_name) DO NOTHING;")

    # Languages
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- LANGUAGE - Languages")
    sections.append("-- =============================================================================")
    sections.append("")
    lang_lines = []
    for i, (code, name) in enumerate(data["languages"]):
        comma = "," if i < len(data["languages"]) - 1 else ""
        c = code.replace("'", "''")
        n = name.replace("'", "''")
        lang_lines.append(f"    ('{c}', '{n}'){comma}")
    sections.append(f"INSERT INTO language (language_code, language_name) VALUES\n" +
                    "\n".join(lang_lines) +
                    "\nON CONFLICT (language_code) DO NOTHING;")

    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- END OF SEED DATA")
    sections.append("-- =============================================================================")
    sections.append("")

    return "\n".join(sections)


def _py_list(name: str, values: list[str], indent: str = "    ") -> str:
    """Format a Python list constant."""
    lines = [f"{name} = ["]
    for v in values:
        lines.append(f'{indent}"{v}",')
    lines.append("]")
    return "\n".join(lines)


def generate_taxonomy_config(data: dict) -> str:
    """Generate taxonomy_config.py content, preserving REFERENCE_EXAMPLES."""
    lines = []
    lines.append('"""')
    lines.append("Taxonomy configuration for the Film Database project.")
    lines.append("")
    lines.append("All valid taxonomy values extracted from database.")
    lines.append("Auto-generated by scripts/export_taxonomy.py — do not edit manually.")
    lines.append("Used by ClaudeEnricher to build prompts and validate outputs.")
    lines.append('"""')
    lines.append("")

    # Categories (main only, no subcategories)
    main_cats = [cat for cat, sub, _ in data["categories"] if sub is None]
    lines.append(_py_list("VALID_CATEGORIES", main_cats))
    lines.append("")

    # Historic subcategories
    hist_subs = [sub for cat, sub, _ in data["categories"] if sub is not None]
    lines.append(_py_list("VALID_HISTORIC_SUBCATEGORIES", hist_subs))
    lines.append("")

    lines.append(_py_list("VALID_CINEMA_TYPES", [name for name, _ in data["cinema_types"]]))
    lines.append("")
    lines.append(_py_list("VALID_PLACE_ENVIRONMENTS", [name for name, _ in data["place_contexts"]]))
    lines.append("")
    lines.append(_py_list("VALID_TIME_CONTEXTS", [name for name, _ in data["time_contexts"]]))
    lines.append("")
    lines.append(_py_list("VALID_THEMES", [name for name, _ in data["themes"]]))
    lines.append("")
    lines.append(_py_list("VALID_CHARACTERS", [name for name, _ in data["characters"]]))
    lines.append("")
    lines.append(_py_list("VALID_ATMOSPHERES", [name for name, _ in data["atmospheres"]]))
    lines.append("")
    lines.append(_py_list("VALID_MOTIVATIONS", [name for name, _ in data["motivations"]]))
    lines.append("")
    lines.append(_py_list("VALID_MESSAGES", [name for name, _ in data["messages"]]))
    lines.append("")
    lines.append(_py_list("VALID_SOURCE_TYPES", [
        "original screenplay", "novel", "comic", "TV series", "true story",
        "play", "video game", "poem", "short story", "remake",
    ]))
    lines.append("")

    # TAXONOMY_DIMENSIONS dict
    lines.append("TAXONOMY_DIMENSIONS = {")
    lines.append('    "categories": VALID_CATEGORIES,')
    lines.append('    "historic_subcategories": VALID_HISTORIC_SUBCATEGORIES,')
    lines.append('    "cinema_type": VALID_CINEMA_TYPES,')
    lines.append('    "time_context": VALID_TIME_CONTEXTS,')
    lines.append('    "place_environment": VALID_PLACE_ENVIRONMENTS,')
    lines.append('    "themes": VALID_THEMES,')
    lines.append('    "character_context": VALID_CHARACTERS,')
    lines.append('    "atmosphere": VALID_ATMOSPHERES,')
    lines.append('    "motivations": VALID_MOTIVATIONS,')
    lines.append('    "message": VALID_MESSAGES,')
    lines.append("}")
    lines.append("")

    # Preserve REFERENCE_EXAMPLES from existing file
    try:
        existing = CONFIG_PATH.read_text(encoding="utf-8")
        marker = "REFERENCE_EXAMPLES = {"
        idx = existing.find(marker)
        if idx >= 0:
            # Find the comment block before REFERENCE_EXAMPLES
            block_start = existing.rfind("# ===", 0, idx)
            if block_start >= 0:
                lines.append(existing[block_start:].rstrip())
            else:
                lines.append(existing[idx:].rstrip())
        lines.append("")
    except FileNotFoundError:
        lines.append("REFERENCE_EXAMPLES = {}")
        lines.append("")

    return "\n".join(lines)


async def main():
    parser = argparse.ArgumentParser(description="Export taxonomy from DB to source files")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing files")
    args = parser.parse_args()

    db_url = os.getenv("DATABASE_URL")
    if not db_url:
        print("ERROR: DATABASE_URL not set in .env", file=sys.stderr)
        sys.exit(1)

    engine = create_async_engine(db_url, echo=False)

    try:
        data = await fetch_all(engine)
    finally:
        await engine.dispose()

    seed_sql = generate_seed_sql(data)
    config_py = generate_taxonomy_config(data)

    if args.dry_run:
        print("=" * 60)
        print("seed_taxonomy.sql")
        print("=" * 60)
        print(seed_sql)
        print()
        print("=" * 60)
        print("taxonomy_config.py")
        print("=" * 60)
        print(config_py)
    else:
        SEED_PATH.write_text(seed_sql, encoding="utf-8")
        print(f"Written: {SEED_PATH}")
        CONFIG_PATH.write_text(config_py, encoding="utf-8")
        print(f"Written: {CONFIG_PATH}")
        print()
        print("Remember to restart the backend if it's running (taxonomy_config.py is loaded at import time).")


if __name__ == "__main__":
    asyncio.run(main())
