"""
Export current taxonomy state from the database into source files.

Regenerates:
  - database/seed_taxonomy.sql
  - backend/app/services/taxonomy_config.py

Usage:
    python scripts/export_taxonomy.py           # overwrite files
    python scripts/export_taxonomy.py --dry-run  # print to stdout
"""

import argparse
import asyncio
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SEED_PATH = PROJECT_ROOT / "database" / "seed_taxonomy.sql"
CONFIG_PATH = PROJECT_ROOT / "backend" / "app" / "services" / "taxonomy_config.py"


async def fetch_all(engine):
    """Fetch all taxonomy data from the database."""
    data = {}
    async with engine.connect() as conn:
        # Categories
        r = await conn.execute(text(
            "SELECT category_name, historic_subcategory_name FROM category "
            "ORDER BY category_name, historic_subcategory_name NULLS FIRST"
        ))
        data["categories"] = r.fetchall()

        # Cinema types
        r = await conn.execute(text("SELECT technique_name FROM cinema_type ORDER BY technique_name"))
        data["cinema_types"] = [row[0] for row in r.fetchall()]

        # Cultural movements
        r = await conn.execute(text("SELECT movement_name FROM cultural_movement ORDER BY movement_name"))
        data["cultural_movements"] = [row[0] for row in r.fetchall()]

        # Place contexts
        r = await conn.execute(text("SELECT environment FROM place_context ORDER BY environment"))
        data["place_contexts"] = [row[0] for row in r.fetchall()]

        # Time contexts (with sort_order)
        r = await conn.execute(text("SELECT time_period, sort_order FROM time_context ORDER BY sort_order, time_period"))
        data["time_contexts"] = [(row[0], row[1]) for row in r.fetchall()]

        # Themes (with sort_order)
        r = await conn.execute(text("SELECT theme_name, sort_order FROM theme_context ORDER BY sort_order, theme_name"))
        data["themes"] = [(row[0], row[1]) for row in r.fetchall()]

        # Characters types
        r = await conn.execute(text("SELECT type_name FROM characters_type ORDER BY type_name"))
        data["characters_types"] = [row[0] for row in r.fetchall()]

        # Character contexts
        r = await conn.execute(text("SELECT context_name FROM character_context ORDER BY context_name"))
        data["character_contexts"] = [row[0] for row in r.fetchall()]

        # Atmospheres
        r = await conn.execute(text("SELECT atmosphere_name FROM atmosphere ORDER BY atmosphere_name"))
        data["atmospheres"] = [row[0] for row in r.fetchall()]

        # Motivations
        r = await conn.execute(text("SELECT motivation_name FROM motivation_relation ORDER BY motivation_name"))
        data["motivations"] = [row[0] for row in r.fetchall()]

        # Messages
        r = await conn.execute(text("SELECT message_name FROM message_conveyed ORDER BY message_name"))
        data["messages"] = [row[0] for row in r.fetchall()]

        # Person jobs
        r = await conn.execute(text("SELECT role_name FROM person_job ORDER BY role_name"))
        data["person_jobs"] = [row[0] for row in r.fetchall()]

        # Streaming platforms
        r = await conn.execute(text("SELECT platform_name FROM stream_platform ORDER BY platform_name"))
        data["streaming_platforms"] = [row[0] for row in r.fetchall()]

        # Languages
        r = await conn.execute(text("SELECT language_code, language_name FROM language ORDER BY language_code"))
        data["languages"] = [(row[0], row[1]) for row in r.fetchall()]

    return data


def _sql_values(values: list[str], indent: str = "    ") -> str:
    """Format a list of strings as SQL VALUES."""
    lines = []
    for i, v in enumerate(values):
        escaped = v.replace("'", "''")
        comma = "," if i < len(values) - 1 else ""
        lines.append(f"{indent}('{escaped}'){comma}")
    return "\n".join(lines)


def generate_seed_sql(data: dict) -> str:
    """Generate the full seed_taxonomy.sql content."""
    sections = []

    sections.append("-- Film Database Seed Data")
    sections.append("-- Pre-populate all taxonomy/lookup tables with reference values")
    sections.append("-- Uses ON CONFLICT DO NOTHING for idempotent execution")
    sections.append("-- Auto-generated by scripts/export_taxonomy.py")

    # Person jobs
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- PERSON_JOB - Crew roles")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["person_jobs"])
    sections.append(f"INSERT INTO person_job (role_name) VALUES\n{vals}\nON CONFLICT (role_name) DO NOTHING;")

    # Categories
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- CATEGORY - Film genres with historical subcategories")
    sections.append("-- =============================================================================")
    sections.append("")
    cat_lines = []
    for i, (cat_name, sub_name) in enumerate(data["categories"]):
        comma = "," if i < len(data["categories"]) - 1 else ""
        cn = cat_name.replace("'", "''")
        if sub_name:
            sn = sub_name.replace("'", "''")
            cat_lines.append(f"    ('{cn}', '{sn}'){comma}")
        else:
            cat_lines.append(f"    ('{cn}', NULL){comma}")
    sections.append(f"INSERT INTO category (category_name, historic_subcategory_name) VALUES\n" +
                    "\n".join(cat_lines) +
                    "\nON CONFLICT (category_name, historic_subcategory_name) DO NOTHING;")

    # Cinema types
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- CINEMA_TYPE - Cinematographic techniques")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["cinema_types"])
    sections.append(f"INSERT INTO cinema_type (technique_name) VALUES\n{vals}\nON CONFLICT (technique_name) DO NOTHING;")

    # Cultural movements
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- CULTURAL_MOVEMENT - Cinematic movements")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["cultural_movements"])
    sections.append(f"INSERT INTO cultural_movement (movement_name) VALUES\n{vals}\nON CONFLICT (movement_name) DO NOTHING;")

    # Place contexts
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- PLACE_CONTEXT - Environmental settings")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["place_contexts"])
    sections.append(f"INSERT INTO place_context (environment) VALUES\n{vals}\nON CONFLICT (environment) DO NOTHING;")

    # Time contexts
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- TIME_CONTEXT - Historical periods and seasons")
    sections.append("-- =============================================================================")
    sections.append("")
    tc_lines = []
    for i, (name, sort_order) in enumerate(data["time_contexts"]):
        comma = "," if i < len(data["time_contexts"]) - 1 else ""
        escaped = name.replace("'", "''")
        tc_lines.append(f"    ('{escaped}', {sort_order}){comma}")
    sections.append(f"INSERT INTO time_context (time_period, sort_order) VALUES\n" +
                    "\n".join(tc_lines) +
                    "\nON CONFLICT (time_period) DO NOTHING;")

    # Themes
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- THEME_CONTEXT - Thematic elements")
    sections.append("-- =============================================================================")
    sections.append("")
    th_lines = []
    for i, (name, sort_order) in enumerate(data["themes"]):
        comma = "," if i < len(data["themes"]) - 1 else ""
        escaped = name.replace("'", "''")
        th_lines.append(f"    ('{escaped}', {sort_order}){comma}")
    sections.append(f"INSERT INTO theme_context (theme_name, sort_order) VALUES\n" +
                    "\n".join(th_lines) +
                    "\nON CONFLICT (theme_name) DO NOTHING;")

    # Characters types
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- CHARACTERS_TYPE - Character configurations")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["characters_types"])
    sections.append(f"INSERT INTO characters_type (type_name) VALUES\n{vals}\nON CONFLICT (type_name) DO NOTHING;")

    # Character contexts
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- CHARACTER_CONTEXT - Character contexts and archetypes")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["character_contexts"])
    sections.append(f"INSERT INTO character_context (context_name) VALUES\n{vals}\nON CONFLICT (context_name) DO NOTHING;")

    # Atmospheres
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- ATMOSPHERE - Film atmosphere/tone")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["atmospheres"])
    sections.append(f"INSERT INTO atmosphere (atmosphere_name) VALUES\n{vals}\nON CONFLICT (atmosphere_name) DO NOTHING;")

    # Motivations
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- MOTIVATION_RELATION - Character motivations")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["motivations"])
    sections.append(f"INSERT INTO motivation_relation (motivation_name) VALUES\n{vals}\nON CONFLICT (motivation_name) DO NOTHING;")

    # Messages
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- MESSAGE_CONVEYED - Film messages")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["messages"])
    sections.append(f"INSERT INTO message_conveyed (message_name) VALUES\n{vals}\nON CONFLICT (message_name) DO NOTHING;")

    # Streaming platforms
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- STREAM_PLATFORM - Streaming platforms")
    sections.append("-- =============================================================================")
    sections.append("")
    vals = _sql_values(data["streaming_platforms"])
    sections.append(f"INSERT INTO stream_platform (platform_name) VALUES\n{vals}\nON CONFLICT (platform_name) DO NOTHING;")

    # Languages
    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- LANGUAGE - Languages")
    sections.append("-- =============================================================================")
    sections.append("")
    lang_lines = []
    for i, (code, name) in enumerate(data["languages"]):
        comma = "," if i < len(data["languages"]) - 1 else ""
        c = code.replace("'", "''")
        n = name.replace("'", "''")
        lang_lines.append(f"    ('{c}', '{n}'){comma}")
    sections.append(f"INSERT INTO language (language_code, language_name) VALUES\n" +
                    "\n".join(lang_lines) +
                    "\nON CONFLICT (language_code) DO NOTHING;")

    sections.append("")
    sections.append("-- =============================================================================")
    sections.append("-- END OF SEED DATA")
    sections.append("-- =============================================================================")
    sections.append("")

    return "\n".join(sections)


def _py_list(name: str, values: list[str], indent: str = "    ") -> str:
    """Format a Python list constant."""
    lines = [f"{name} = ["]
    for v in values:
        lines.append(f'{indent}"{v}",')
    lines.append("]")
    return "\n".join(lines)


def generate_taxonomy_config(data: dict) -> str:
    """Generate taxonomy_config.py content, preserving REFERENCE_EXAMPLES."""
    lines = []
    lines.append('"""')
    lines.append("Taxonomy configuration for the Film Database project.")
    lines.append("")
    lines.append("All valid taxonomy values extracted from database.")
    lines.append("Auto-generated by scripts/export_taxonomy.py — do not edit manually.")
    lines.append("Used by ClaudeEnricher to build prompts and validate outputs.")
    lines.append('"""')
    lines.append("")

    # Categories (main only, no subcategories)
    main_cats = [cat for cat, sub in data["categories"] if sub is None]
    lines.append(_py_list("VALID_CATEGORIES", main_cats))
    lines.append("")

    # Historic subcategories
    hist_subs = [sub for cat, sub in data["categories"] if sub is not None]
    lines.append(_py_list("VALID_HISTORIC_SUBCATEGORIES", hist_subs))
    lines.append("")

    lines.append(_py_list("VALID_CINEMA_TYPES", data["cinema_types"]))
    lines.append("")
    lines.append(_py_list("VALID_CULTURAL_MOVEMENTS", data["cultural_movements"]))
    lines.append("")
    lines.append(_py_list("VALID_PLACE_ENVIRONMENTS", data["place_contexts"]))
    lines.append("")
    lines.append(_py_list("VALID_TIME_CONTEXTS", [name for name, _ in data["time_contexts"]]))
    lines.append("")
    lines.append(_py_list("VALID_THEMES", [name for name, _ in data["themes"]]))
    lines.append("")
    lines.append(_py_list("VALID_CHARACTERS_TYPES", data["characters_types"]))
    lines.append("")
    lines.append(_py_list("VALID_CHARACTER_CONTEXTS", data["character_contexts"]))
    lines.append("")
    lines.append(_py_list("VALID_ATMOSPHERES", data["atmospheres"]))
    lines.append("")
    lines.append(_py_list("VALID_MOTIVATIONS", data["motivations"]))
    lines.append("")
    lines.append(_py_list("VALID_MESSAGES", data["messages"]))
    lines.append("")
    lines.append(_py_list("VALID_SOURCE_TYPES", [
        "original screenplay", "novel", "comic", "TV series", "true story",
        "play", "video game", "poem", "short story", "remake",
    ]))
    lines.append("")

    # TAXONOMY_DIMENSIONS dict
    lines.append("TAXONOMY_DIMENSIONS = {")
    lines.append('    "categories": VALID_CATEGORIES,')
    lines.append('    "historic_subcategories": VALID_HISTORIC_SUBCATEGORIES,')
    lines.append('    "cinema_type": VALID_CINEMA_TYPES,')
    lines.append('    "cultural_movement": VALID_CULTURAL_MOVEMENTS,')
    lines.append('    "time_context": VALID_TIME_CONTEXTS,')
    lines.append('    "place_environment": VALID_PLACE_ENVIRONMENTS,')
    lines.append('    "themes": VALID_THEMES,')
    lines.append('    "characters_type": VALID_CHARACTERS_TYPES,')
    lines.append('    "character_context": VALID_CHARACTER_CONTEXTS,')
    lines.append('    "atmosphere": VALID_ATMOSPHERES,')
    lines.append('    "motivations": VALID_MOTIVATIONS,')
    lines.append('    "message": VALID_MESSAGES,')
    lines.append("}")
    lines.append("")

    # Preserve REFERENCE_EXAMPLES from existing file
    try:
        existing = CONFIG_PATH.read_text(encoding="utf-8")
        marker = "REFERENCE_EXAMPLES = {"
        idx = existing.find(marker)
        if idx >= 0:
            # Find the comment block before REFERENCE_EXAMPLES
            block_start = existing.rfind("# ===", 0, idx)
            if block_start >= 0:
                lines.append(existing[block_start:].rstrip())
            else:
                lines.append(existing[idx:].rstrip())
        lines.append("")
    except FileNotFoundError:
        lines.append("REFERENCE_EXAMPLES = {}")
        lines.append("")

    return "\n".join(lines)


async def main():
    parser = argparse.ArgumentParser(description="Export taxonomy from DB to source files")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing files")
    args = parser.parse_args()

    db_url = os.getenv("DATABASE_URL")
    if not db_url:
        print("ERROR: DATABASE_URL not set in .env", file=sys.stderr)
        sys.exit(1)

    engine = create_async_engine(db_url, echo=False)

    try:
        data = await fetch_all(engine)
    finally:
        await engine.dispose()

    seed_sql = generate_seed_sql(data)
    config_py = generate_taxonomy_config(data)

    if args.dry_run:
        print("=" * 60)
        print("seed_taxonomy.sql")
        print("=" * 60)
        print(seed_sql)
        print()
        print("=" * 60)
        print("taxonomy_config.py")
        print("=" * 60)
        print(config_py)
    else:
        SEED_PATH.write_text(seed_sql, encoding="utf-8")
        print(f"Written: {SEED_PATH}")
        CONFIG_PATH.write_text(config_py, encoding="utf-8")
        print(f"Written: {CONFIG_PATH}")
        print()
        print("Remember to restart the backend if it's running (taxonomy_config.py is loaded at import time).")


if __name__ == "__main__":
    asyncio.run(main())
