const FLAGS: Record<string, string> = {
  American: "🇺🇸",
  English: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  British: "🇬🇧",
  Scottish: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Welsh: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Irish: "🇮🇪",
  French: "🇫🇷",
  German: "🇩🇪",
  Italian: "🇮🇹",
  Spanish: "🇪🇸",
  Portuguese: "🇵🇹",
  Dutch: "🇳🇱",
  Belgian: "🇧🇪",
  Swiss: "🇨🇭",
  Austrian: "🇦🇹",
  Swedish: "🇸🇪",
  Norwegian: "🇳🇴",
  Danish: "🇩🇰",
  Finnish: "🇫🇮",
  Icelandic: "🇮🇸",
  Polish: "🇵🇱",
  Czech: "🇨🇿",
  Slovak: "🇸🇰",
  Hungarian: "🇭🇺",
  Romanian: "🇷🇴",
  Bulgarian: "🇧🇬",
  Greek: "🇬🇷",
  Turkish: "🇹🇷",
  Russian: "🇷🇺",
  Ukrainian: "🇺🇦",
  Serbian: "🇷🇸",
  Croatian: "🇭🇷",
  Bosnian: "🇧🇦",
  Slovenian: "🇸🇮",
  Japanese: "🇯🇵",
  Korean: "🇰🇷",
  "South Korean": "🇰🇷",
  Chinese: "🇨🇳",
  "Hong Kong": "🇭🇰",
  "Hong Konger": "🇭🇰",
  Taiwanese: "🇹🇼",
  Indian: "🇮🇳",
  Pakistani: "🇵🇰",
  Bangladeshi: "🇧🇩",
  Vietnamese: "🇻🇳",
  Thai: "🇹🇭",
  Indonesian: "🇮🇩",
  Filipino: "🇵🇭",
  Malaysian: "🇲🇾",
  Singaporean: "🇸🇬",
  Iranian: "🇮🇷",
  Israeli: "🇮🇱",
  Lebanese: "🇱🇧",
  Egyptian: "🇪🇬",
  Moroccan: "🇲🇦",
  Algerian: "🇩🇿",
  Tunisian: "🇹🇳",
  "South African": "🇿🇦",
  Nigerian: "🇳🇬",
  Kenyan: "🇰🇪",
  Brazilian: "🇧🇷",
  Argentine: "🇦🇷",
  Argentinian: "🇦🇷",
  Chilean: "🇨🇱",
  Mexican: "🇲🇽",
  Cuban: "🇨🇺",
  Colombian: "🇨🇴",
  Peruvian: "🇵🇪",
  Venezuelan: "🇻🇪",
  Canadian: "🇨🇦",
  Australian: "🇦🇺",
  "New Zealander": "🇳🇿",
  Kiwi: "🇳🇿",
};

export function getNationalityFlag(nationality: string | null): string {
  if (!nationality) return "";
  return FLAGS[nationality] ?? FLAGS[nationality.trim()] ?? "";
}
